export const CHANGE_SELECTED_TYPE = 'CHANGE_SELECTED_TYPE';
export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const UPDATE_MESSAGES = 'UPDATE_MESSAGES';
export const ON_SELECT_LIST = 'ON_SELECT_LIST';
export const CLEAR_SELECTED = 'CLEAR_SELECTED';
export const DELETE_SELECTED = 'DELETE_SELECTED';